export const FETCH_BOARD_LIST = 'FETCH_BOARD_LIST'
export const FETCH_BOARD = 'FETCH_BOARD'


export const FETCH_LOGIN = 'FETCH_LOGIN'

export const FETCH_GONGZI_LIST = 'FETCH_GONGZI_LIST'
export const FETCH_GONGZI = 'FETCH_GONGZI'

export const CRAWL_START = 'CRAWL_START'